### ISSUE TITLE
Action commits access token

### ISSUE THREAD

**Issue by MichaelFlucher** [taichi/actions-package-update#23]
The Action somehow managed to commit the `env.sh` file containing the access token to Github.
https://github.com/Catrobat/Catblocks/blob/c81c15c6cb3d0db750c125a40000f5273aca2a0b/env.sh

Fortunately Github instantly blocked the Token.

**Comment by Ghustavh97** [comment]
@MichaelFlucher sorry for this, i'm the one who created that stupid bug. I fixed it in less than 24 hours tho here: https://github.com/taichi/actions-package-update/pull/21 .

**Comment by MichaelFlucher** [comment]
ok
